local k = vim.keymap.set
local builtin = require('telescope.builtin')

k('n', '<leader>o', function() require('oil').toggle_float() end, { desc = 'Open oil in a floating window' })
k('v', '<M-c>', '"+y', { desc = 'Copy selection to system clipboard'})
k('n', '<M-s>', '<cmd>noh<cr>', { desc = 'Clears selection'})
k('n', '<leader>a', 'ggVG', { desc = 'Select all text', silent = true })
k('n', '<C-h>', '<cmd>wincmd h<cr>', { desc='Go to the left split', silent=true })
k('n', '<C-j>', '<cmd>wincmd j<cr>', { desc='Go to the bottom spit', silent=true })
k('n', '<C-k>', '<cmd>wincmd k<cr>', { desc='Go to the top split', silent=true })
k('n', '<C-l>', '<cmd>wincmd l<cr>', { desc='Go to the right split', silent=true })
k('n', '<leader>ff', builtin.find_files, { desc = 'Telescope find files' })
k('n', '<leader>fg', builtin.live_grep, { desc = 'Telescope live grep' })
k('n', '<leader>fb', builtin.buffers, { desc = 'Telescope buffers' })
k('n', '<leader>fh', builtin.help_tags, { desc = 'Telescope help tags' })
k('n', '<M-h>', '<cmd>bprev<cr>', {desc='Goto previous buffer',silent=true})
k('n', '<M-l>', '<cmd>bnext<cr>', {desc='Goto next buffer',silent=true})
k('n', '<M-q>', '<cmd>bd<cr>', { desc='Closes current buffer', silent=true })
k('n', '<M-Q>', '<cmd>bd!<cr>', { desc='Closes current buffer without saving the file', silent=true })
k('n', '<leader>e', '<cmd>NvimTreeToggle<cr>', { desc = 'Toggles NvimTree' })
k('n', '<M-i>', '<cmd>tabp<cr>', { desc = 'Moveds on to the previous tab' })
k('n', '<M-p>', '<cmd>tabn<cr>', { desc = 'Moveds on to the next tab' })
k('n', '<leader>gg', '<cmd>Neogit<cr>', { desc = 'Opens Neogit' })
